[pytest]
addopts =
    --basetemp=.pytest_cache/temp
    --cov=core
    --cov=db
    --cov=logger
    --cov=url_normalizer
    --cov=vinted_notifications
    --cov=pyVintedVN
    --cov=telegram_bot_plugin
    --cov=rss_feed_plugin
    --cov=web_ui_plugin
    --cov-report=term
    --cov-fail-under=48
testpaths = tests
